### ISSUE TITLE
too high logging throughput makes  our app unresponsive

### ISSUE THREAD

**Issue by stubbi** [boxfuse/cloudwatchlogs-java-appender#8]
We had a hard time last week to understand why our system went down regularly. But finally we managed by some black box testing to find at least which component seems to be responsible for our frequent downtimes.

It turns out that the log appender seems not to handle our amount of logs (>=20logs/sec) we are sending to it. When we send the logs, the app is not responding anymore and thus boxfuse eventually redeploys it.

We still wonder how this can be the case as the appender should be able to handle much more throughput. We are using the latest version 1.1.3.33, Unfortunately, we can't tell more about the exact error as we won't see anything in the logs nor can't we access the application. What we can tell from our debugging with New Relic and jxm though, is that there seems every thing alright with the memory, threads and open connections on our server.

We found that the logappender is to blame for our downtime when we reduced the functionality of some of our components to only perform some logging and nothing else. When we finally also disabled that, our system became stable again.

To be precisely, I can change the behavior of our backend from a mostly stable to an unstable system by changing:

```
<!-- boxfuse aws -->
  <appender name="Boxfuse-CloudwatchLogs" class="com.boxfuse.cloudwatchlogs.logback.CloudwatchLogsLogbackAppender"/>

  <root level="INFO">
    <appender-ref ref="Boxfuse-CloudwatchLogs" />
  </root>
```

to

```
<!-- boxfuse aws -->
  <appender name="Boxfuse-CloudwatchLogs" class="com.boxfuse.cloudwatchlogs.logback.CloudwatchLogsLogbackAppender"/>

  <root level="DEBUG">
    <appender-ref ref="Boxfuse-CloudwatchLogs" />
  </root>
```

**Comment by axelfontaine** [comment]
Hmmm this is not a whole lot to go on...

- Are you able to recreate this locally by sending a lot of load to your instance as it is running on VirtualBox?
- Do you have any unusually large debug message being guarded by `isDebugEnabled()` checks from your logging framework?
- How exactly is it failing? Gradually or suddenly? Do you see any indication it is about to fail?

**Comment by tasuk** [comment]
- We don't use VirtualBox for development (it's slow). We can however try to test this.
- We don't send any unusually large messages. They're all <100 characters.
- No indication it's about to fail. It fails gradually, sometimes even comes back (depending on the amount of log messages being sent).

**Comment by axelfontaine** [comment]
I have just committed a new test that exercises the non-AWS SDK part of the code and it easily achieves 250,000 log messages per second on my machine. So I do not believe the error lies in our code.

Feel free to run it yourself to verify and/or point out any flaws.

**Comment by teldosas** [comment]
@axelfontaine could it be that the appender is not dealing well with the aws cloudwatch rate limiting http://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html ?

**Comment by axelfontaine** [comment]
Even if it wasn't (and it is, see https://github.com/boxfuse/cloudwatchlogs-java-appender/blob/master/src/main/java/com/boxfuse/cloudwatchlogs/internal/CloudwatchLogsLogEventPutter.java#L190) they appender is fully async. The appender writes the log events into a concurrent and bounded data structure and then flushes them to CloudWatch Logs in a separate thread.

**Comment by teldosas** [comment]
@axelfontaine if a lot of threads try to push events to they appender the would have to do it `synchronized`, (one by one) right? Could it be that our server becomes unresponsive cause a lot of threads are waiting for the logs to get appended?

**Comment by axelfontaine** [comment]
No. The data structures are concurrent. Please check out the code. It's all there. https://github.com/boxfuse/cloudwatchlogs-java-appender/search?utf8=%E2%9C%93&q=synchronized&type=

Also have a play with the test I committed. Even with 1000 threads in parallel each pushing 1000 messages, the appender still manage to complete processing in about 4 seconds at 250000 events/sec.

**Comment by teldosas** [comment]
Ok, I looked at the code for a bit but I'm not an expert in concurrency. So I'll just thrown one assumption more and maybe you will prove me wrong again.

So could it be that too many connections to the cloudwatch api get opened and that's the reason for our app becoming unresponsive?

**Comment by axelfontaine** [comment]
Again, the appender is fully asynchronous and can never cause your application to block. Your application threads only write to the concurrent data structure and return immediately. A separate thread in the appender then consumes the events and sends them to CloudWatch Logs in batches.

**Comment by tasuk** [comment]
@axelfontaine ok, perhaps it's not a mistake in your code, however, it doesn't work and it's a big problem for us.

Either of the following two changes fixes our issue:

1.
```
<root level="DEBUG">
  <appender-ref ref="Boxfuse-CloudwatchLogs" />
</root>
```
to 
```
<root level="INFO">
  <appender-ref ref="Boxfuse-CloudwatchLogs" />
</root>
```

2. in our code (in a place where we generate ~20 log entries per second): `logger.debug("Some not too long message")` to `logger.info("Some not too long message")` (where `logger` is an instance of `play.api.Logger`).

What are the possible explanations for this behaviour other than blaming the Boxfuse Cloudwatch appender?

**Comment by tasuk** [comment]
In other words, it is the _combination_ of the appender logging debug logs AND the logger receiving debug logs that breaks our system.

**Comment by tasuk** [comment]
Not a stupid question at all!

**Comment by tasuk** [comment]
@axelfontaine, we have the following versions:
```
com.amazonaws:aws-java-sdk-logs:1.11.51
com.typesafe.play:play_2.11:2.5.4
ch.qos.logback:logback-core:1.1.7
org.slf4j:slf4j-api:1.7.21
```

**Comment by axelfontaine** [comment]
@tasuk Have you been able to upgrade all dependencies to see if the problem persists?

**Comment by teldosas** [comment]
@axelfontaine after upgrading the problem persists. Can you try testing high logging throughput with actually sending logs to cloudwatch enabled?

**Comment by teldosas** [comment]
is it possible that the appender is not dealing well with cloudwatch rate limiting http://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html ?

**Comment by tasuk** [comment]
@axelfontaine any news on this?

**Comment by axelfontaine** [comment]
@tasuk We're currently performing a number of tests. I'll keep you updated.

**Comment by axelfontaine** [comment]
We have now completed our tests. We uncovered a case where very high volumes of log messages caused the check for the maximum batch size to be bypassed and AWS call to fail. We have fixed this and released version 1.1.4.40. In our tests (also included in the repository under the new largetest module) we sent 1,000,000 log events as fast as possible via multiple threads through the appender and averaged 15,000 log events per second being sent to AWS with 0 errors.

Please give the new version a try and let us know whether this resolves your issue.

**Comment by tasuk** [comment]
Axel, that's awesome - thank you very much!

**Comment by teldosas** [comment]
Actually our problem is not fixed after upgrading to `1.1.4.40` the server still becomes unresponsive

**Comment by axelfontaine** [comment]
FYI, we released 1.1.5.46 last week. It does however not contain any fixes which I feel could be relevant here, but you never know...

Either way the search continues. I must say I can't think of a place where the appender could be at fault anymore. Feel free to inspect the code (it's all here), run the tests and contradict me.

If that avenue doesn't yield anything, it may be time for you to try and reproduce this issue locally in VirtualBox on your machine and remote debug the issue or get a thread dump using New Relic or with JMX using JVisualVM and see where each thread is waiting. Also if you are on t2 instances, monitor CPU credits and look for a possible exhaustion in CloudWatch (New Relic should also clearly show this with CPU stolen time).

**Comment by teldosas** [comment]
The problem persisted even after updating to the version above.

We could only resolve the problem by disabling the appender and letting the [cloudwatchlogs-agent](https://github.com/boxfuse/cloudwatchlogs-agent) send the console logs to cloudwatch

**Comment by axelfontaine** [comment]
Thanks for the update. This is very strange. Were you able to debug it and pinpoint the exact lines of code causing the issue?

**Comment by teldosas** [comment]
Unfortunately not

**Comment by axelfontaine** [comment]
Closing as we haven't been able to reproduce this.
